### ISSUE TITLE
Support for emojis 🙏

### ISSUE THREAD

**Issue by gogl92** [dasmer/restaurant-menu-generator#1]
I wanted to add emojis to the CSV file but I got this exception.

```
Traceback (most recent call last):
  File "piatto.py", line 12, in <module>
    for item in csv:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 108, in next
    row = self.reader.next()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 136-139: ordinal not in range(128)
```

Any ideas? Really simple and useful project though.

Thanks

**Comment by enric1994** [comment]
Hey! We just released CSV2Menu inspired by Piatto. Check it out! https://github.com/enric1994/csv2menu
We support emojis, allergens and calories!

**Comment by gogl92** [comment]
I know this was like 3 years ago but I tested it now and it's working!
